# Use the official Tomcat base image
FROM tomcat:10.0-jdk11

# Copy the WAR file from the Downloads folder to the Tomcat webapps directory
COPY C:/Users/Gerald/Downloads/JADCA2.war /usr/local/tomcat/webapps/ROOT.war

# Expose port 8080 for web traffic
EXPOSE 8080

# Start Tomcat Server
CMD ["catalina.sh", "run"]
